export const reqdemo = {
  type: "requestMiddleWare",
  data: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false,
    },
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
    headers: {
      common: { Accept: "application/json, text/plain, */*" },
      delete: {},
      get: {},
      head: {},
      post: { "Content-Type": "application/x-www-form-urlencoded" },
      put: { "Content-Type": "application/x-www-form-urlencoded" },
      patch: { "Content-Type": "application/x-www-form-urlencoded" },
    },
    baseURL: "https://api-velkoz.haiyaogame.com/api/",
    method: "get",
    url: "/heracles/board/boards/banner",
  },
};
export const resdemo = {
  type: "responseMiddleWare",
  data: {
    status: 200,
    statusText: "OK",
    headers: {
      date: "Tue, 05 Dec 2023 08:57:24 GMT",
      "content-type": "application/json",
      "content-length": "1014",
      connection: "close",
      vary: "Origin, Access-Control-Request-Method, Access-Control-Request-Headers",
    },
    config: {
      transitional: {
        silentJSONParsing: true,
        forcedJSONParsing: true,
        clarifyTimeoutError: false,
      },
      transformRequest: [null],
      transformResponse: [null],
      timeout: 10000,
      xsrfCookieName: "XSRF-TOKEN",
      xsrfHeaderName: "X-XSRF-TOKEN",
      maxContentLength: -1,
      maxBodyLength: -1,
      headers: { main_token: "", client_id: "", "User-Agent": "axios/0.24.0" },
      baseURL: "https://api-velkoz.haiyaogame.com/api/",
      method: "get",
      url: "/heracles/board/boards/banner",
      timeoutErrorMessage: "network timeout",
    },
    request: {
      _events: {},
      _eventsCount: 7,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: "",
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: {
        _tlsOptions: {
          pipe: false,
          secureContext: { context: {} },
          isServer: false,
          requestCert: true,
          rejectUnauthorized: true,
          session: { type: "Buffer", data: [] },
        },
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        secureConnecting: false,
        _SNICallback: null,
        servername: "api-velkoz.haiyaogame.com",
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: { close: [null, null, null, null], timeout: [null, null] },
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: "api-velkoz.haiyaogame.com",
        _closeAfterHandlingError: false,
        _readableState: {
          objectMode: false,
          highWaterMark: 16384,
          buffer: { head: null, tail: null, length: 0 },
          length: 0,
          pipes: [],
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          constructed: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          errorEmitted: false,
          emitClose: false,
          autoDestroy: true,
          destroyed: false,
          errored: null,
          closed: false,
          closeEmitted: false,
          defaultEncoding: "utf8",
          awaitDrainWriters: null,
          multiAwaitDrain: false,
          readingMore: false,
          dataEmitted: true,
          decoder: null,
          encoding: null,
        },
        _writableState: {
          objectMode: false,
          highWaterMark: 16384,
          finalCalled: true,
          needDrain: false,
          ending: true,
          ended: true,
          finished: false,
          destroyed: false,
          decodeStrings: false,
          defaultEncoding: "utf8",
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          writecb: null,
          writelen: 0,
          afterWriteTickInfo: null,
          buffered: [],
          bufferedIndex: 0,
          allBuffers: true,
          allNoop: true,
          pendingcb: 1,
          constructed: true,
          prefinished: false,
          errorEmitted: false,
          emitClose: false,
          autoDestroy: true,
          errored: null,
          closed: false,
          closeEmitted: false,
        },
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: "",
        _server: null,
        ssl: {
          _parent: { reading: true, onconnection: null },
          _parentWrap: null,
          _secureContext: "[Circular]",
          reading: true,
        },
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: "[Circular]",
        timeout: 10000,
      },
      _header:
        "GET /api/heracles/board/boards/banner HTTP/1.1\r\nmain_token: \r\nclient_id: \r\nUser-Agent: axios/0.24.0\r\nHost: xxx.xx.com\r\nConnection: close\r\n\r\n",
      _keepAliveTimeout: 0,
      agent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: "https:",
        options: { noDelay: true, path: null },
        requests: {},
        sockets: {
          "api-velkoz.haiyaogame.com:443:::::::::::::::::::::": ["[Circular]"],
        },
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: "lifo",
        maxTotalSockets: null,
        totalSocketCount: 1,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {
            "telemetry.nextjs.org:443:::::::::::::::::::::": {
              type: "Buffer",
              data: [],
            },
            "api-velkoz.haiyaogame.com:443:::::::::::::::::::::": {
              type: "Buffer",
              data: [],
            },
          },
          list: [
            "telemetry.nextjs.org:443:::::::::::::::::::::",
            "api-velkoz.haiyaogame.com:443:::::::::::::::::::::",
          ],
        },
      },
      method: "GET",
      path: "/api/heracles/board/boards/banner",
      _ended: true,
      res: {
        _readableState: {
          objectMode: false,
          highWaterMark: 16384,
          buffer: { head: null, tail: null, length: 0 },
          length: 0,
          pipes: [],
          flowing: true,
          ended: true,
          endEmitted: true,
          reading: false,
          constructed: true,
          sync: true,
          needReadable: false,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          errorEmitted: false,
          emitClose: true,
          autoDestroy: true,
          destroyed: true,
          errored: null,
          closed: true,
          closeEmitted: true,
          defaultEncoding: "utf8",
          awaitDrainWriters: null,
          multiAwaitDrain: false,
          readingMore: true,
          dataEmitted: true,
          decoder: null,
          encoding: null,
        },
        _events: { end: [null, null] },
        _eventsCount: 3,
        socket: "[Circular]",
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: "1.1",
        complete: true,
        rawHeaders: [
          "Date",
          "Tue, 05 Dec 2023 08:57:24 GMT",
          "Content-Type",
          "application/json",
          "Content-Length",
          "1014",
          "Connection",
          "close",
          "Vary",
          "Origin",
          "Vary",
          "Access-Control-Request-Method",
          "Vary",
          "Access-Control-Request-Headers",
        ],
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: "",
        method: null,
        statusCode: 200,
        statusMessage: "OK",
        client: "[Circular]",
        _consuming: false,
        _dumped: false,
        req: "[Circular]",
        responseUrl:
          "https://api-velkoz.haiyaogame.com/api/heracles/board/boards/banner",
        redirects: [],
      },
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: "api-velkoz.haiyaogame.com",
      protocol: "https:",
      _redirectable: {
        _writableState: {
          objectMode: false,
          highWaterMark: 16384,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: false,
          decodeStrings: true,
          defaultEncoding: "utf8",
          length: 0,
          writing: false,
          corked: 0,
          sync: true,
          bufferProcessing: false,
          writecb: null,
          writelen: 0,
          afterWriteTickInfo: null,
          buffered: [],
          bufferedIndex: 0,
          allBuffers: true,
          allNoop: true,
          pendingcb: 0,
          constructed: true,
          prefinished: false,
          errorEmitted: false,
          emitClose: true,
          autoDestroy: true,
          errored: null,
          closed: false,
          closeEmitted: false,
        },
        _events: {},
        _eventsCount: 3,
        _options: {
          maxRedirects: 21,
          maxBodyLength: 10485760,
          protocol: "https:",
          path: "/api/heracles/board/boards/banner",
          method: "GET",
          headers: "[Circular]",
          agents: {},
          hostname: "api-velkoz.haiyaogame.com",
          port: null,
          nativeProtocols: {
            "http:": {
              METHODS: [
                "ACL",
                "BIND",
                "CHECKOUT",
                "CONNECT",
                "COPY",
                "DELETE",
                "GET",
                "HEAD",
                "LINK",
                "LOCK",
                "M-SEARCH",
                "MERGE",
                "MKACTIVITY",
                "MKCALENDAR",
                "MKCOL",
                "MOVE",
                "NOTIFY",
                "OPTIONS",
                "PATCH",
                "POST",
                "PROPFIND",
                "PROPPATCH",
                "PURGE",
                "PUT",
                "REBIND",
                "REPORT",
                "SEARCH",
                "SOURCE",
                "SUBSCRIBE",
                "TRACE",
                "UNBIND",
                "UNLINK",
                "UNLOCK",
                "UNSUBSCRIBE",
              ],
              STATUS_CODES: {
                "100": "Continue",
                "101": "Switching Protocols",
                "102": "Processing",
                "103": "Early Hints",
                "200": "OK",
                "201": "Created",
                "202": "Accepted",
                "203": "Non-Authoritative Information",
                "204": "No Content",
                "205": "Reset Content",
                "206": "Partial Content",
                "207": "Multi-Status",
                "208": "Already Reported",
                "226": "IM Used",
                "300": "Multiple Choices",
                "301": "Moved Permanently",
                "302": "Found",
                "303": "See Other",
                "304": "Not Modified",
                "305": "Use Proxy",
                "307": "Temporary Redirect",
                "308": "Permanent Redirect",
                "400": "Bad Request",
                "401": "Unauthorized",
                "402": "Payment Required",
                "403": "Forbidden",
                "404": "Not Found",
                "405": "Method Not Allowed",
                "406": "Not Acceptable",
                "407": "Proxy Authentication Required",
                "408": "Request Timeout",
                "409": "Conflict",
                "410": "Gone",
                "411": "Length Required",
                "412": "Precondition Failed",
                "413": "Payload Too Large",
                "414": "URI Too Long",
                "415": "Unsupported Media Type",
                "416": "Range Not Satisfiable",
                "417": "Expectation Failed",
                "418": "I'm a Teapot",
                "421": "Misdirected Request",
                "422": "Unprocessable Entity",
                "423": "Locked",
                "424": "Failed Dependency",
                "425": "Too Early",
                "426": "Upgrade Required",
                "428": "Precondition Required",
                "429": "Too Many Requests",
                "431": "Request Header Fields Too Large",
                "451": "Unavailable For Legal Reasons",
                "500": "Internal Server Error",
                "501": "Not Implemented",
                "502": "Bad Gateway",
                "503": "Service Unavailable",
                "504": "Gateway Timeout",
                "505": "HTTP Version Not Supported",
                "506": "Variant Also Negotiates",
                "507": "Insufficient Storage",
                "508": "Loop Detected",
                "509": "Bandwidth Limit Exceeded",
                "510": "Not Extended",
                "511": "Network Authentication Required",
              },
              maxHeaderSize: 16384,
              globalAgent: {
                _events: {},
                _eventsCount: 2,
                defaultPort: 80,
                protocol: "http:",
                options: { noDelay: true, path: null },
                requests: {},
                sockets: {},
                freeSockets: {},
                keepAliveMsecs: 1000,
                keepAlive: false,
                maxSockets: null,
                maxFreeSockets: 256,
                scheduling: "lifo",
                maxTotalSockets: null,
                totalSocketCount: 0,
              },
            },
            "https:": { globalAgent: "[Circular]" },
          },
          pathname: "/api/heracles/board/boards/banner",
        },
        _ended: true,
        _ending: true,
        _redirectCount: 0,
        _redirects: "[Circular]",
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _currentRequest: "[Circular]",
        _currentUrl:
          "https://api-velkoz.haiyaogame.com/api/heracles/board/boards/banner",
        _timeout: null,
      },
    },
    data: [
      {
        id: 22,
        imageUrl:
          "https://kassadin.fsource.io/0933d218aff242388c7cc7d8981096bc.png",
        linkUrl: "/lottery-jackpot",
        group: "banner",
        groupName: "主页Banner",
        description: "",
        weight: 30,
        tags: null,
        tagNames: null,
        createTime: 1676885092,
      },
      {
        id: 7,
        imageUrl:
          "https://kassadin.fsource.io/65b5fa23a9b74d7c9a990c2397e913f5.png",
        linkUrl: "/activity/deposit/deposit-reward-slots-game",
        group: "banner",
        groupName: "主页Banner",
        description: "",
        weight: 25,
        tags: "id",
        tagNames: null,
        createTime: 1663755407,
      },
      {
        id: 24,
        imageUrl:
          "https://kassadin.fsource.io/b451fcbe67d7479cb9538ae84280d7d8.png",
        linkUrl: "/daily-wins",
        group: "banner",
        groupName: "主页Banner",
        description: "",
        weight: 24,
        tags: "id",
        tagNames: null,
        createTime: 1685084506,
      },
      {
        id: 5,
        imageUrl:
          "https://kassadin.fsource.io/467160fe0c484249978a442e92805fa3.png",
        linkUrl: "/activity/deposit/deposit-reward-all-game",
        group: "banner",
        groupName: "主页Banner",
        description: "",
        weight: 20,
        tags: "id",
        tagNames: null,
        createTime: 1663326629,
      },
    ],
  },
};
